import { jsx as _jsx } from "react/jsx-runtime";
import '../customTransitions.css';
import LogoLoop from '../LogoLoop';
import { SiHtml5, SiCss3, SiJavascript, SiTypescript, SiReact, SiNextdotjs, SiRedux, SiTailwindcss, SiSass, SiBootstrap, SiVite, SiGit, SiFigma, SiMui, SiChakraui, SiStyledcomponents, SiWebpack, SiEslint, SiPrettier, SiStorybook, SiCypress, SiFramer, SiGreensock, SiThreedotjs, SiBlender, SiSvg, SiNodedotjs, SiExpress, SiMongodb, SiPostgresql, SiMysql, SiGraphql, SiDocker, SiFirebase, SiPrisma, SiPython, SiDjango, SiApollographql, SiSwagger, SiRedis, SiSupabase, SiNetlify, SiVercel, SiHeroku, SiJest, SiMocha, SiGithubactions, SiKalilinux, SiWireshark, SiMetasploit, SiBurpsuite, SiLinux, SiGnubash, SiGithub, SiOwasp, SiTorbrowser, SiOpenssl, SiVirtualbox, SiVmware, SiGooglecloud, SiMarkdown, SiNotion, SiSlack, SiTrello, SiJira, SiZapier } from 'react-icons/si';
const techLogos = [
    { node: _jsx(SiHtml5, {}), title: "HTML5", href: "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5" },
    { node: _jsx(SiCss3, {}), title: "CSS3", href: "https://developer.mozilla.org/en-US/docs/Web/CSS" },
    { node: _jsx(SiJavascript, {}), title: "JavaScript", href: "https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
    { node: _jsx(SiTypescript, {}), title: "TypeScript", href: "https://www.typescriptlang.org" },
    { node: _jsx(SiReact, {}), title: "React", href: "https://react.dev" },
    { node: _jsx(SiNextdotjs, {}), title: "Next.js", href: "https://nextjs.org" },
    { node: _jsx(SiRedux, {}), title: "Redux", href: "https://redux.js.org/" },
    { node: _jsx(SiTailwindcss, {}), title: "Tailwind CSS", href: "https://tailwindcss.com" },
    { node: _jsx(SiSass, {}), title: "Sass", href: "https://sass-lang.com/" },
    { node: _jsx(SiBootstrap, {}), title: "Bootstrap", href: "https://getbootstrap.com/" },
    { node: _jsx(SiVite, {}), title: "Vite", href: "https://vitejs.dev/" },
    { node: _jsx(SiGit, {}), title: "Git", href: "https://git-scm.com/" },
    { node: _jsx(SiFigma, {}), title: "Figma", href: "https://figma.com/" },
    { node: _jsx(SiMui, {}), title: "Material UI", href: "https://mui.com/" },
    { node: _jsx(SiChakraui, {}), title: "Chakra UI", href: "https://chakra-ui.com/" },
    { node: _jsx(SiStyledcomponents, {}), title: "Styled Components", href: "https://styled-components.com/" },
    { node: _jsx(SiWebpack, {}), title: "Webpack", href: "https://webpack.js.org/" },
    { node: _jsx(SiEslint, {}), title: "ESLint", href: "https://eslint.org/" },
    { node: _jsx(SiPrettier, {}), title: "Prettier", href: "https://prettier.io/" },
    { node: _jsx(SiStorybook, {}), title: "Storybook", href: "https://storybook.js.org/" },
    { node: _jsx(SiCypress, {}), title: "Cypress", href: "https://www.cypress.io/" },
    { node: _jsx(SiFramer, {}), title: "Framer Motion", href: "https://www.framer.com/motion/" },
    { node: _jsx(SiGreensock, {}), title: "GSAP", href: "https://greensock.com/gsap/" },
    { node: _jsx(SiThreedotjs, {}), title: "Three.js", href: "https://threejs.org/" },
    { node: _jsx(SiBlender, {}), title: "Blender", href: "https://www.blender.org/" },
    { node: _jsx(SiSvg, {}), title: "SVG", href: "https://developer.mozilla.org/en-US/docs/Web/SVG" },
    { node: _jsx(SiNodedotjs, {}), title: "Node.js", href: "https://nodejs.org/" },
    { node: _jsx(SiExpress, {}), title: "Express", href: "https://expressjs.com/" },
    { node: _jsx(SiMongodb, {}), title: "MongoDB", href: "https://www.mongodb.com/" },
    { node: _jsx(SiPostgresql, {}), title: "PostgreSQL", href: "https://www.postgresql.org/" },
    { node: _jsx(SiMysql, {}), title: "MySQL", href: "https://www.mysql.com/" },
    { node: _jsx(SiGraphql, {}), title: "GraphQL", href: "https://graphql.org/" },
    { node: _jsx(SiDocker, {}), title: "Docker", href: "https://www.docker.com/" },
    { node: _jsx(SiFirebase, {}), title: "Firebase", href: "https://firebase.google.com/" },
    { node: _jsx(SiPrisma, {}), title: "Prisma", href: "https://www.prisma.io/" },
    { node: _jsx(SiPython, {}), title: "Python", href: "https://www.python.org/" },
    { node: _jsx(SiDjango, {}), title: "Django", href: "https://www.djangoproject.com/" },
    { node: _jsx(SiApollographql, {}), title: "Apollo GraphQL", href: "https://www.apollographql.com/" },
    { node: _jsx(SiSwagger, {}), title: "Swagger", href: "https://swagger.io/" },
    { node: _jsx(SiRedis, {}), title: "Redis", href: "https://redis.io/" },
    { node: _jsx(SiSupabase, {}), title: "Supabase", href: "https://supabase.com/" },
    { node: _jsx(SiNetlify, {}), title: "Netlify", href: "https://www.netlify.com/" },
    { node: _jsx(SiVercel, {}), title: "Vercel", href: "https://vercel.com/" },
    { node: _jsx(SiHeroku, {}), title: "Heroku", href: "https://www.heroku.com/" },
    { node: _jsx(SiJest, {}), title: "Jest", href: "https://jestjs.io/" },
    { node: _jsx(SiMocha, {}), title: "Mocha", href: "https://mochajs.org/" },
    { node: _jsx(SiGithubactions, {}), title: "GitHub Actions", href: "https://github.com/features/actions" },
    { node: _jsx(SiKalilinux, {}), title: "Kali Linux", href: "https://www.kali.org/" },
    { node: _jsx(SiWireshark, {}), title: "Wireshark", href: "https://www.wireshark.org/" },
    { node: _jsx(SiMetasploit, {}), title: "Metasploit", href: "https://www.metasploit.com/" },
    { node: _jsx(SiBurpsuite, {}), title: "Burp Suite", href: "https://portswigger.net/burp" },
    { node: _jsx(SiLinux, {}), title: "Linux", href: "https://www.linux.org/" },
    { node: _jsx(SiGnubash, {}), title: "Bash", href: "https://www.gnu.org/software/bash/" },
    { node: _jsx(SiGithub, {}), title: "GitHub", href: "https://github.com/" },
    { node: _jsx(SiOwasp, {}), title: "OWASP", href: "https://owasp.org/" },
    { node: _jsx(SiTorbrowser, {}), title: "Tor", href: "https://www.torproject.org/" },
    { node: _jsx(SiOpenssl, {}), title: "OpenSSL", href: "https://www.openssl.org/" },
    { node: _jsx(SiVirtualbox, {}), title: "VirtualBox", href: "https://www.virtualbox.org/" },
    { node: _jsx(SiVmware, {}), title: "VMware", href: "https://www.vmware.com/" },
    { node: _jsx(SiGooglecloud, {}), title: "Google Cloud", href: "https://cloud.google.com/" },
    { node: _jsx(SiMarkdown, {}), title: "Markdown", href: "https://www.markdownguide.org/" },
    { node: _jsx(SiNotion, {}), title: "Notion", href: "https://www.notion.so/" },
    { node: _jsx(SiSlack, {}), title: "Slack", href: "https://slack.com/" },
    { node: _jsx(SiTrello, {}), title: "Trello", href: "https://trello.com/" },
    { node: _jsx(SiJira, {}), title: "Jira", href: "https://www.atlassian.com/software/jira" },
    { node: _jsx(SiZapier, {}), title: "Zapier", href: "https://zapier.com/" },
];
function Logoloop() {
    return (_jsx("div", { className: "logoloop-container", children: _jsx(LogoLoop, { logos: techLogos, speed: 60, direction: "left", logoHeight: 55, gap: 80, hoverSpeed: 20, scaleOnHover: true, fadeOut: true, fadeOutColor: "#ffffff", ariaLabel: "Technology partners" }) }));
}
export default Logoloop;
